// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADko6w2ikhlJcPRmA1EqPiyB06T1FxglI',
    appId: '1:1051367927550:web:7cb64e034e4a9c6171bfaf',
    messagingSenderId: '1051367927550',
    projectId: 'friendly-tower-470411-t3',
    authDomain: 'friendly-tower-470411-t3.firebaseapp.com',
    storageBucket: 'friendly-tower-470411-t3.firebasestorage.app',
    measurementId: 'G-N5GEHC6T4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9JuzUljYJRp-iZ-3i95c_R3rE4B7nYnA',
    appId: '1:1051367927550:android:dd635591976ed97671bfaf',
    messagingSenderId: '1051367927550',
    projectId: 'friendly-tower-470411-t3',
    storageBucket: 'friendly-tower-470411-t3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrZH_4O4NK3D8DoaNl53ivuKN-8whAVHI',
    appId: '1:1051367927550:ios:410f5e1da34e0e0771bfaf',
    messagingSenderId: '1051367927550',
    projectId: 'friendly-tower-470411-t3',
    storageBucket: 'friendly-tower-470411-t3.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );
}
